#!/usr/bin/env ruby

require 'bundler/setup'
require 'daemons'

Daemons.run(File.join(File.expand_path(__FILE__),'..','..','lib','apprentice.rb'), :dir_mode => :normal, :dir => File.join(File.expand_path(__FILE__),'..','..','tmp','pids'), :monitor => true)

# require_relative '../lib/apprentice'

# Daemons.run_proc('apprentice', :dir => 'tmp/pids', :dir_mode => :normal, :monitor => true) do
#   loop do
#     WatchMeMakeThis::Apprentice.run
#     sleep 10
#   end
# end
